### ISSUE TITLE
When is the plan to support for azure blob storage via jcloud?

### ISSUE THREAD

**Issue by SumanSwati** [SAP-samples/cloud-objectstore-java-sample#3]
Hi All

We wanted to use object-store for persisting .tar/.mtar content. For now, our services are available on aws and azure landscape. We wanted to avoid writing native queries for each of the IaaS providers and hence wanted to use _jcloud_ for doing the same.

Since, jcloud already support sas-token way of authentication in azure blob-storage. So we wanted to do POC via jcloud on azure blob-storage as well as aws s3. But we are not sure, if jcloud would work for azure. If you guys can confirm, we will use jcloud for both.

We followed this document, but we could not get support of jcloud for azure. 
https://developers.sap.com/tutorials/cp-objectstore-mc-java-app.html

Thanks
Swati

**Comment by SumanSwati** [comment]
This ticket might be useful for the above purpose:
https://issues.apache.org/jira/browse/JCLOUDS-1428?focusedCommentId=16998110&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16998110

**Comment by biswaranjanray** [comment]
Hi Swati,

Azure Storage is now supported in ObjectStore reference application for internal customers. Please find the [github](https://github.wdf.sap.corp/refapps/objectstore-sample/tree/azure-storage) link. 
The application is currently adapted to JClouds 2.2.0 which internally make references to Guava 16.0. Guava 16.0 apis are basically deprecated. Though this issue is resolved but the fix will be available in future release JClouds 2.3.0 . Please refer the [JIRA](https://issues.apache.org/jira/browse/JCLOUDS-1491) ticket to know more.

At the moment it may not be feasible to ship the application for external users as it refers to deprecated version of Guava library and this could also be a concern to raise an approval request.

Thanks,
Biswa Ranjan
